name: 'Update Profile README'

on:
  # schedule:
    # - cron: '0 */12 * * *'  # Alle 12 Stunden
  workflow_dispatch:  # Manuelles Triggern

permissions:
  contents: write
  actions: read
  
jobs:
  collect-categories:
    name: 'Generate JSON data'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Get all public repositories from the organization
        id: repos
        run: |
          organization="${{ github.repository_owner }}"
          repositories_url="https://api.github.com/orgs/$organization/repos?type=public"
          
          blacklist=()
          while IFS= read -r line; do
              blacklist+=("$line")
          done < "./blacklist.txt"
          
          echo "Fetching all public repositories for \"$organization\"..."
          repositories_response=$(curl -s $repositories_url)
          
          repository_names=$(echo "$repositories_response" | jq -r '.[].name')

          echo "::group:: Found the following repositories:"
          echo "$repository_names" | sed 's/[^ ]*/- &/g'
          echo "::endgroup::"
          
          category_data="{
            \"categories\": []
          }"

          echo "Processing repositories..."
          for repository_name in $repository_names; do
              echo "::group:: Processing \"$repository_name\""
              
              if [[ " ${blacklist[@]} " =~ " $repository_name " ]]; then
                  echo "::warning:: Ignoring repository \"$repository_name\" due to blacklist."
                  echo "::endgroup::"
                  continue
              fi
              
              repository_url="https://github.com/$organization/$repository_name"
              labels_url="https://api.github.com/repos/$organization/$repository_name/labels"
              
              echo "Fetching labels..."
              labels_response=$(curl -s $labels_url)

              echo "Searching for \"category: \" prefix..."
              category=$(echo "$labels_response" | jq -r '.[] | select(.name | startswith("category: ")) | .name' | sed 's/category: //')

              if [[ -z "$category" ]]; then
                  echo "::warning:: Ignoring repository \"$repository_name\" because no category was found."
                  echo "::endgroup::"
                  continue
              fi
              
              echo "Found label category \"$category\"."
              
              echo "Generating JSON entry..."
              category_data=$(echo "$category_data" | jq \
                --arg category "$category" \
                --arg repository_url "$repository_url" \
                --arg repository_name "$repository_name" \
                '
                  if (.categories | map(select(.id == $category)) | length > 0) then
                    .categories |= map(
                      if .id == $category then
                        .repositories += [{"url": $repository_url, "name": $repository_name}]
                      else . end
                    )
                  else
                    .categories += [{"id": $category, "repositories": [{"url": $repository_url, "name": $repository_name}]}]
                  end
                ')
                
              echo "::endgroup::"
          done

          echo "::group:: Done generating JSON data"
          echo "$category_data" | jq .
          echo "::endgroup::"
          echo "$category_data" > category_data.json
