name: Collect and Generate Profile README

on:
  # schedule:
    # - cron: '0 */12 * * *'  # Alle 12 Stunden
  workflow_dispatch:  # Manuelles Triggern

permissions:
  contents: write
  actions: read
  
jobs:
  collect-categories:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Get all public repositories from the organization
        id: repos
        run: |
          organization="${{ github.repository_owner }}"
          repositories_url="https://api.github.com/orgs/$organization/repos?type=public"
          blacklist=(".github" "Template" "default")
          
          echo "Fetching all public repositories for \"$organization\"..."
          repositories_response=$(curl -s $repositories_url)
          
          repository_names=$(echo "$repositories_response" | jq -r '.[].name')

          echo "::group:: Found the following repositories:"
          echo '- $(sed -e "s/\n- /$repository_names/")'
          echo "::endgroup::"
          
          category_data="{
            \"categories\": []
          }"

          for repository_name in $repository_names; do
              
              echo "::group:: Processing \"$repository_name\""
              
              if [[ " ${blacklist[@]} " =~ " $repository_name " ]]; then
                  echo "::warning:: Ignoring repository \"$repository_name\" due to blacklist."
                  continue
              fi
              
              
              repository_url="https://github.com/$organization/$repository_name"
              labels_url="https://api.github.com/repos/$organization/$repository_name/labels"

              labels_response=$(curl -s $labels_url)
              
              category=$(echo "$labels_response" | jq -r '.[] | select(.name | startswith("category: ")) | .name' | sed 's/category: //')

              if [[ -z "$category" ]]; then
                  echo "No category found for repository $repository_name"
                  continue
              fi

              category_data=$(echo "$category_data" | jq \
                --arg category "$category" \
                --arg repository_url "$repository_url" \
                --arg repository_name "$repository_name" \
                '
                  if (.categories | map(select(.id == $category)) | length > 0) then
                    .categories |= map(
                      if .id == $category then
                        .repositories += [{"url": $repository_url, "name": $repository_name}]
                      else . end
                    )
                  else
                    .categories += [{"id": $category, "repositories": [{"url": $repository_url, "name": $repository_name}]}]
                  end
                ')
                
              echo "::endgroup::"
          done

          echo "$category_data" > category_data.json
          echo $category_data
