name: Collect and Generate Profile README

on:
  # schedule:
    # - cron: '0 */12 * * *'  # Alle 12 Stunden
  workflow_dispatch:  # Manuelles Triggern

permissions:
  contents: write
  actions: read
  
jobs:
  collect-categories:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Get all public repositories from the organization
        id: repos
        run: |
          organization="${{ github.repository_owner }}"
          repositories_url="https://api.github.com/orgs/$organization/repos?type=public"
          
          blacklist=(".github" "Template" "default")

          repositories_response=$(curl -s $repositories_url)

          echo $repositories_response
          
          repository_names=$(echo "$repositories_response" | jq -r '.[].name')

          echo $repository_names
          
          category_data="{
            \"categories\": []
          }"

          for repository_name in $repository_names; do
              if [[ " ${blacklist[@]} " =~ " $repository_name " ]]; then
                  echo "Ignoring repository $repository_name due to blacklist"
                  continue
              fi
              
              echo "Processing: $repository_name"
              
              repository_url="https://github.com/$organization/$repository_name"
              labels_url="https://api.github.com/repos/$organization/$repository_url/labels"

              labels_response=$(curl -s $labels_url)

              echo $labels_response
              
              category=$(echo "$labels_response" | jq -r '.[] | select(.name | startswith("category: ")) | .name' | sed 's/category: //')

              if [[ -z "$category" ]]; then
                  echo "No category found for repository $repo_name"
                  continue
              fi

              category_data=$(echo "$category_data" | jq \
                --arg category "$category" \
                --arg repo_url "$repository_url" \
                --arg repo_name "$repository_name" \
                '
                  if (.categories | map(select(.id == $category)) | length > 0) then
                    .categories |= map(
                      if .id == $category then
                        .repositories += [{"url": $repository_url, "name": $repository_name}]
                      else . end
                    )
                  else
                    .categories += [{"id": $category, "repositories": [{"url": $repository_url, "name": $repository_name}]}]
                  end
                ')

          done

          echo "$category_data" > category_data.json

      - name: Create README from categories data
        run: |
          readme_template=$(cat profile/template/readme.md)
          category_template=$(cat profile/template/category.md)
          repository_template=$(cat profile/template/repository.md)
          
          categories=$(cat category_data.json | jq -c '.categories')

          echo "readme.md:"
          echo $readme_template
          echo "category.md:"
          echo $category_template
          echo "repository.md:"
          echo $repository_template
          echo "Categories JSON:"
          echo $categories

          template=$(cat profile/README.md)

          for category in $(echo "$categories" | jq -r '.id'); do
            category_name=$category
            repositories=$(echo "$categories" | jq -r ".[] | select(.id == \"$category_name\") | .repositories[] | \"$repository_template\"")

            category_section=$(echo "$category_template" | sed "s/\${category_name}/$category_name/" | sed "s/\${repositories}/$repositories/")

            template="$template$category_section"
          done

          echo -e "$template" > profile/README.md

      - name: Commit and push changes to README
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/README.md
          git commit -m "Update profile README with latest repositories"
          git push origin main
