name: Collect and Generate Profile README

on:
  # schedule:
    # - cron: '0 */12 * * *'  # Alle 12 Stunden
  workflow_dispatch:  # Manuelles Triggern

jobs:
  collect-categories:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Get all public repositories from the organization
        id: repos
        run: |
          org="Datapack-Registry"  # Name der Organisation
          repos_url="https://api.github.com/orgs/$org/repos?type=public"
          
          # Blacklist definieren
          blacklist=("Template" "default")

          # Fetch all public repositories
          repos_response=$(curl -s $repos_url)
          
          # Filtern, dass wir nur öffentliche Repositories bekommen
          repo_names=$(echo "$repos_response" | jq -r '.[].name')

          category_data="{
            \"categories\": []
          }"

          for repo_name in $repo_names; do
              # Repository auf Blacklist prüfen
              if [[ " ${blacklist[@]} " =~ " $repo_name " ]]; then
                  echo "Ignoring repository $repo_name due to blacklist"
                  continue
              fi

              repo_url="https://github.com/$org/$repo_name"
              labels_url="https://api.github.com/repos/$org/$repo_name/labels"

              # Abrufen der Labels für das Repository
              labels_response=$(curl -s $labels_url)
              
              # Prüfen, ob Labels vorhanden sind, und die Kategorie extrahieren
              category=$(echo "$labels_response" | jq -r '.[] | select(.name | startswith("category: ")) | .name' | sed 's/category: //')

              if [[ -z "$category" ]]; then
                  echo "No category found for repository $repo_name"
                  continue
              fi

              # Kategorie-Daten zur JSON hinzufügen
              category_data=$(echo "$category_data" | jq \
                --arg category "$category" \
                --arg repo_url "$repo_url" \
                --arg repo_name "$repo_name" \
                '
                  if (.categories | map(select(.id == $category)) | length > 0) then
                    .categories |= map(
                      if .id == $category then
                        .repositories += [{"url": $repo_url, "name": $repo_name}]
                      else . end
                    )
                  else
                    .categories += [{"id": $category, "repositories": [{"url": $repo_url, "name": $repo_name}]}]
                  end
                ')

          done

          # JSON-Datei speichern
          echo "$category_data" > category_data.json

      - name: Load README Template
        id: load_readme_template
        run: |
          # Lade das Template für die README.md Datei
          readme_template=$(cat profile/template/readme.md)
          echo "$readme_template" > profile/README.md

      - name: Load Category Template
        id: load_category_template
        run: |
          # Lade das Template für die Kategorie-Sektion
          category_template=$(cat profile/template/category.md)

      - name: Load Repository Template
        id: load_repository_template
        run: |
          # Lade das Template für die Repository-Sektion
          repository_template=$(cat profile/template/repository.md)

      - name: Create README from categories data
        run: |
          # Lade die gesammelten Kategorien
          categories=$(cat category_data.json | jq -r '.categories[]')

          # Beginne mit der Template für die README
          template=$(cat profile/README.md)

          # Kategorien aus der JSON lesen und formatieren
          for category in $(echo "$categories" | jq -r '.id'); do
            category_name=$category
            repositories=$(echo "$categories" | jq -r ".[] | select(.id == \"$category_name\") | .repositories[] | \"$repository_template\"")

            # Kategorie-Sektion erstellen
            category_section=$(echo "$category_template" | sed "s/\${category_name}/$category_name/" | sed "s/\${repositories}/$repositories/")

            # Kategorie-Sektion zu Template hinzufügen
            template="$template$category_section"
          done

          # Endgültige README.md-Datei speichern
          echo -e "$template" > profile/README.md

      - name: Commit and push changes to README
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add profile/README.md
          git commit -m "Update profile README with latest repositories"
          git push origin main
